### ISSUE TITLE
Voir la carte à l'avance ne donne pas de sentiment de "découverte"

### ISSUE THREAD

**Issue by Herondil** [Dev1-2017-2018/colony24#46]
Si le joueur doit explorer le monde du jeu, lui montrer toute la carte change un peu le sentiment, pour l'or on ira forcément sur les zones jaunes.

**Comment by Yekonori** [comment]
Problème réglé pour la map dans la console.

**Comment by Herondil** [comment]
Okay, pour considérer qu'un problème a été résolu, vous pouvez cliquer sur "close and comment"
