### ISSUE TITLE
Pas de message "Votre bateau est retourné au port"

### ISSUE THREAD

**Issue by Herondil** [Dev1-2017-2018/colony24#47]
Si j'envoie le premier bateau en 1-1, il y a bien écrit qu'il récolte de l'or.

Si je le renvoie en 1-1, il récolte et ensuite revient au port.

**Comment by Yekonori** [comment]
![image](https://user-images.githubusercontent.com/25904840/33760942-c3605668-dc07-11e7-99a9-76d39166f1ee.png)
